"""
Core configuration and default parameters for the APMCM Problem C question 3
model. Paths are resolved relative to this repository root to keep usage
portable in this workspace.
"""

from __future__ import annotations

from pathlib import Path
from typing import Dict, List

# -----------------------------
# Paths
# -----------------------------

PROJECT_ROOT = Path(__file__).resolve().parent

# Cleaned data generated by wash/datawash.py
CLEAN_DATA_DIR = PROJECT_ROOT / "wash" / "output"

# Raw supporting data (used when available, otherwise the model falls back to
# defaults). We locate subdirectories by substring to avoid issues with
# non-ASCII folder names on Windows consoles.
RAW_DATA_DIR = PROJECT_ROOT / "external_data"

# -----------------------------
# Model dimensions
# -----------------------------

REGIONS: List[str] = ["US", "CN", "ROW"]  # United States, China, Rest of World
CHIP_TYPES: List[str] = ["H", "M", "L"]   # High / Mid / Low end

BASE_YEAR: int = 2023
HIST_YEARS: List[int] = [2020, 2021, 2022, 2023]
SIM_YEARS: List[int] = [2023, 2024, 2025, 2026, 2027, 2028, 2029]

# Discount factor for intertemporal objective
DISCOUNT: float = 0.96

# -----------------------------
# Elasticities and intensities (baseline guesses; can be calibrated)
# -----------------------------

# Armington substitution elasticities by chip type.
# USITC NAICS 334413 micro estimates给出约 3.3；高端可替代性更低、低端更高。
DEFAULT_SIGMA: Dict[str, float] = {"H": 2.0, "M": 3.3, "L": 4.0}

# Final demand price elasticities by region and chip type
# Flamm/BEA/ITIF 等对 ICT 需求的估计落在 0.5-1.5 左右（取绝对值），高端最不敏感。
DEFAULT_EPSILON: Dict[str, Dict[str, float]] = {
    "US": {"H": 0.8, "M": 1.2, "L": 1.5},
    "CN": {"H": 0.9, "M": 1.2, "L": 1.5},
    "ROW": {"H": 0.9, "M": 1.2, "L": 1.4},
}

# Supply elasticities by region and chip type
# 短期供给弹性文献区间 0.5-1（长期可至 ~3）；取短期偏低、中低端略高。
DEFAULT_SUPPLY_ELASTICITY: Dict[str, Dict[str, float]] = {
    "US": {"H": 0.8, "M": 1.0, "L": 1.2},
    "CN": {"H": 1.0, "M": 1.2, "L": 1.4},
    "ROW": {"H": 1.0, "M": 1.2, "L": 1.3},
}

# R&D intensity (share of sales); US aligned with SIA Factbook ~19.5%
DEFAULT_RD_INTENSITY: Dict[str, Dict[str, float]] = {
    "US": {"H": 0.195, "M": 0.195, "L": 0.195},
    "CN": {"H": 0.14, "M": 0.12, "L": 0.10},
    "ROW": {"H": 0.11, "M": 0.11, "L": 0.10},
}

# R&D to technology progress coefficients（高技行业文献 0.10-0.20 区间，取偏中）
TECH_PROGRESS_COEF: Dict[str, float] = {"H": 0.12, "M": 0.08, "L": 0.05}

# Default technology levels at base year (relative to US=1.0)
TECH_INITIAL_LEVEL: Dict[str, Dict[str, float]] = {
    "US": {"H": 1.0, "M": 1.0, "L": 1.0},
    "CN": {"H": 0.6, "M": 0.8, "L": 0.9},
    "ROW": {"H": 0.8, "M": 0.9, "L": 0.95},
}

# Chip type shares within HS8542 (fallback if DataWeb parsing fails), aligned with
# WSTS/SIA product structure: high ~55%, mid ~30%, low ~15%
DEFAULT_ALPHA_HML: Dict[str, float] = {"H": 0.55, "M": 0.30, "L": 0.15}

# Within-memory split: share of 854232 treated as high-end HBM/DRAM
DEFAULT_HBM_SHARE: float = 0.20

# Domestic share placeholder for Armington calibration when import data are
# incomplete.
DEFAULT_DOMESTIC_SHARE: float = 0.55

# National security weights
SECURITY_WEIGHTS: Dict[str, float] = {"H": 0.5, "M": 0.3, "L": 0.2}
TECH_GAP_WEIGHT: float = 0.5    # mu
SECURITY_VS_WELFARE: float = 0.3  # lambda

# Very large tariff number to approximate embargo
VERY_LARGE_TARIFF: float = 9e2

# Small epsilon to avoid divide-by-zero
EPS: float = 1e-9

# Dynamic feedback parameters
DEMAND_GROWTH_RATE: float = 0.02  # annual demand shifter growth (2% default)
TECH_FEEDBACK_SUPPLY: float = 0.2  # how strongly tech gains raise supply shifter
